ktor {
    deployment {
        port = ${PORT}
    }
    application {
        modules = [ kz.ruccola.food.ApplicationKt.module, kz.ruccola.food.ApplicationKt.configureDatabase ]
    }
    db {
        url = ${DB_URL}
        user = ${DB_USER}
        password = ${DB_PASSWORD}
    }
    storage {
        path = ${STORAGE_PATH}
    }
    jwt {
        domain = ${JWT_DOMAIN}
        audience = ${JWT_AUDIENCE}
        realm = "kz.ruccola.food"
        secret = ${JWT_SECRET}
    }
}
