ktor {
    deployment {
        port = ${PORT}
    }
    application {
        modules = [ kz.ruccola.food.ApplicationKt.module, kz.ruccola.food.ApplicationKt.configureDatabase ]
    }
    db {
        url = ${DB_URL}
        user = ${DB_USER}
        password = ${DB_PASSWORD}
    }
    storage {
        path = "server/files"
    }
}
