package kz.ruccola.food

object Strings {
    // Tabs
    const val tabPlans = "Цены"
    const val tabDishes = "Блюда"
    const val tabMealPlanDays = "Расписание"
    const val tabCustomers = "Клиенты"
    const val tabSettings = "Настройки"

    // Chats
    const val chatEmpty = "Нет сообщений"
    const val chatMessagePlaceholder = "Введите сообщение"

    // Settings
    const val screenSettingsTitle = "Настройки"
    const val themeSectionTitle = "Тема"
    const val themeSystem = "Системная"
    const val themeLight = "Светлая"
    const val themeDark = "Темная"

    const val editPersonalInfoTitle = "Редактировать личную информацию"
    const val firstName = "Имя"
    const val lastName = "Фамилия"
    const val address = "Адрес"
    const val cancel = "Отмена"
    const val save = "Сохранить"
    const val saving = "Сохранение..."
    const val saveFailed = "Не удалось сохранить"
    const val logOut = "Выйти"

    // Meal types
    const val mealBreakfast = "Завтрак"
    const val mealBrunch = "Второй завтрак"
    const val mealLunch = "Обед"
    const val mealAfternoonSnack = "Полдник"
    const val mealDinner = "Ужин"

    // Auth
    const val login = "Войти"
    const val register = "Регистрация"
    const val email = "Email"
    const val password = "Пароль"
    const val confirmPassword = "Подтвердите пароль"
    const val loggingIn = "Вход..."
    const val registering = "Регистрация..."
    const val loginFailed = "Ошибка входа"
    const val registerFailed = "Ошибка регистрации"
    const val goToRegister = "Зарегистрироваться"
    const val backToLogin = "Назад к входу"

    // Common
    const val errorPrefix = "Ошибка: %s"
    const val noVariants = "Без вариантов"
    const val withVariants = "С вариантами"
    const val periodDays = "Период дней"
    const val noPlansAvailable = "Нет доступных планов для выбранной опции"
    const val labelPricePerDay = "Цена за день: %s"
    const val formatKcal = "%s ккал"
    const val loading = "Загрузка..."
    const val error = "Ошибка"
    const val retry = "Повторить"
    const val delete = "Удалить"
    const val archive = "Архив"
    const val edit = "Редактировать"
    const val add = "Добавить"
    const val create = "Создать"
    const val update = "Обновить"
    const val search = "Поиск"
    const val filter = "Фильтр"
    const val clear = "Очистить"
    const val apply = "Применить"
    const val close = "Закрыть"
    const val ok = "ОК"
    const val yes = "Да"
    const val no = "Нет"
    const val name = "Название"
    const val description = "Описание"
    const val variantDescription = "Описание варианта"
    const val newVariant = "Новый вариант"
    const val editVariant = "Изменить вариант"
    const val searchCustomers = "Поиск клиентов по имени"
    const val noCustomersFound = "Клиенты не найдены"
    const val bindCustomer = "Привязать клиента"
    const val price = "Цена"
    const val calories = "Калории"
    const val labelCustomers = "Клиенты: %s"
    const val noCustomersBound = "Клиенты не привязаны"
    const val image = "Изображение"
    const val images = "Изображения"
    const val noData = "Нет данных"
    const val noItems = "Нет элементов"
    const val newDish = "Новое блюдо"
    const val editDish = "Изменить блюдо"
    const val editName = "Изменить название"
    const val editDescription = "Изменить описание"
    const val variants = "Варианты"
}
